// Warning: this file is automatically generated on 04-08-2019 10-44-23.
// Changes made to this file will be overriden.
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
void compute__concat_concat_1_concat_2(float* t1,float* concat,float* concat_1,float* concat_2);
